### ISSUE TITLE
Integrate Langchain / Llama-index to query over documents

### ISSUE THREAD

**Issue by kaneda2004** [szczyglis-dev/py-gpt#2]
I've been tinkering around with using Langchain / llama-index to vector embed documents and then run OpenAI LLM queries over the vector embeddings.. I think this would be a great addition to PYGPT -- happy to collaborate on it with you if need be -- just checking to see if there's any interest in this on your end?

https://github.com/jerryjliu/llama_index

https://github.com/hwchase17/langchain

Thanks

**Comment by szczyglis-dev** [comment]
Thanks for the suggestions!

Of course! These options have been in the plans for a long time, and all will be implemented, including something I'd like to have that works like AutoGPT, but is easier to use than AutoGPT. All these options will be done, but a little later, because at the moment, unfortunately, I have a bit of other things on my mind related to everyday life.

Thanks again and best regards!

**Comment by szczyglis-dev** [comment]
We'll deal with that, of course we do! ;)

**Comment by szczyglis-dev** [comment]
Langchain is already integrated (from PyGPT version >= 2.0.0).

Vector databases support coming soon ;)
