### ISSUE TITLE
Download files from chat

### ISSUE THREAD

**Issue by supersvetodiod** [szczyglis-dev/py-gpt#25]
Hi. Great app. All in one place. It's just great.!! YOU are the best. Question, when using Chat with file LLAMA, I need to get an answer in the form of a specific file format. For example, in docx. The chat says that it has created a response . Where is this created file located?

**Comment by szczyglis-dev** [comment]
Thank you! The files are saved in the `data` folder in your working directory (you can find the full path in the `Files` tab at the bottom), but you have to first ask to save to a file so that the model can execute the save command (`save_file`). This will only work for text-based data, such as plain text, CSV, JSON, etc. Binary formats cannot be generated in this way.
