### ISSUE TITLE
Web search

### ISSUE THREAD

**Issue by 7SoKKoS7** [szczyglis-dev/py-gpt#69]
when responding from the AI ​​assistant, I receive answers in the chat in the form of AI assistant
~###~
{"cmd": "goal_update", "params": {"status": "pause"}}
~###~
Can I find the error in which file and fix it?

**Comment by szczyglis-dev** [comment]
Please disable the Agent (inline) plugin - this is a plugin command and if you use model like 3.5 it can make mistakes and call the command "pause". This is not related to Web search plugin.

**Comment by jhorner6511** [comment]
> Please disable the Agent (inline) plugin - this is a plugin command and if you use model like 3.5 it can make mistakes and call the command "pause". This is not related to Web search plugin.

On the same topic (rather than opening a new issue) I cannot figure out how to get web results. I have web search enabled, I've added both my google API keys (Search & CX), I've tried all three google models, and still can't get web results. I've also enabled real-time, System (OS), API Calls and my regular API key in settings.

I've also read through your documentation online and followed the instructions, and still nothing.

I'm currently running it on LMDE6 via Snap.
